### ISSUE TITLE
Automatic download command is broken

### ISSUE THREAD

**Issue by kevinmingtarja** [dgraph-io/Install-Dgraph#27]
https://dgraph.io/docs/deploy/download/#automatic-download

The command given here (`curl https://get.dgraph.io -sSf | bash`) gave an error. I think we can remove this section as the "Manual Download" is not that complicated.

![Screen Shot 2022-10-06 at 12 27 17](https://user-images.githubusercontent.com/69668484/194401965-4bf58fc5-eb47-4ad3-a5eb-f619aa53397a.png)

**Comment by MichelDiz** [comment]
Update. I think the issue is with binary asset.

I think we should filter out Beta, RC and etc from the Get Dgraph install line. It doesn't look a safe thing let users install it right away. We should Put as explicitly requested only.

**Comment by MichelDiz** [comment]
Okay, this is temporarily fixed directly on the server. The fix needs review. See https://github.com/dgraph-io/Install-Dgraph/pull/28

**Comment by matthewmcneely** [comment]
We're dropping this (automatic download) in v22.0.0, right?

**Comment by MichelDiz** [comment]
No, this one will be skipped cuz it is a RC. Not a official release. When it comes it will be picked by the script.

**Comment by kevinmingtarja** [comment]
Hi @MichelDiz , the other day @matthewmcneely @meghalims and I, we were highly considering dropping this automatic download feature, since the manual download is not that complicated to do. Do you think we should keep this?

**Comment by MichelDiz** [comment]
Yes, we should keep. Cuz it is better for manual testing, some users and customers uses it. It is not an expensive process to maintain. I see no strong reason to remove it.

A difficulty, I think, for example, having any instance (e.g. EC2) from scratch. Just to test Dgraph. I would have to install Docker, download the image. But if I don't want to use docker I would have to extract the binary from inside the container to the host OS. This add more complexity. Rather than simply running a script. See?

OR, I have to download the binary from Github. Which is exactly the same as this script right? but automated.

In the end, I just wanted to do a quick test. Where I can change parameters and have a more direct control of the execution. Instead of editing a Docker or Docker compose command.

I do this a lot, I don't use Docker all the time. Only when it's necessary. If I need to do something at lightning speed, I use this script. And many others use it too.

**Comment by matthewmcneely** [comment]
@MichelDiz Are you saying you use the auto download for Linux on amd64? Because we don't build for any other platforms, right?

**Comment by MichelDiz** [comment]
Yes, I use Linux in virtual machine on my NAS, I use WSL and stuff. For me it is more comfortable to have this script. And if we get support for other operating systems again. That script would be useful.

**Comment by MichelDiz** [comment]
We can decrease the frequency that this functionality appears in docs or on the main company website. But this kind of script is almost cultural among tech startups. And it's not expensive to maintain.

**Comment by matthewmcneely** [comment]
I see, I guess we thought a wget/curl and an unzip was easier to document than maintaining that script. @meghalims your call to make?
